### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by playbrawlstars** [AaronTraas/Clash-Royale-Clan-Tools#1]
Traceback (most recent call last):
  File "/usr/local/bin/crtools", line 11, in <module>
    load_entry_point('crtools==1.2.0', 'console_scripts', 'crtools')()
  File "/usr/local/lib/python3.6/dist-packages/crtools-1.2.0-py3.6.egg/crtools/__init__.py", line 76, in main
    build_dashboard(api_key, clan_id, logo_path, favicon_path, description_path, output_path)
  File "/usr/local/lib/python3.6/dist-packages/crtools-1.2.0-py3.6.egg/crtools/crtools.py", line 134, in build_dashboard
    clan_description = clan['description']
KeyError: 'description'

**Comment by AaronTraas** [comment]
This is fixed in 1.8. Now gives proper error message when it can't connect to the API
